inClub.Web/Portal/Models/Community.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Healthware.HP3.Core.User.ObjectValues;
using Healthware.HP3.MVC.Attributes;
using Inclub.Web.Portal.Keys;


namespace Inclub.Web.Portal.Models
{


    public class ProponiGruppo
    {

        [Required(ErrorMessage = "Compilare il Titolo")]
        public string Title { get; set; }

        public string Description { get; set; }
        public bool Success { get; set; }

    
    }

}

inClub.Web/Portal/Controllers/CommunityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Healthware.HP3.Core.Content;
using Healthware.HP3.Core.Content.ObjectValues;
using Healthware.HP3.Core.User;
using Healthware.HP3.Core.User.ObjectValues;
using Inclub.Web.Portal.Models;
using Inclub.Web.Portal.BL;
using Inclub.Web.Portal.Keys;
using Healthware.HP3.Core.Site.ObjectValues;
using System.Data.SqlClient;
using System.Data;
using Inclub.Web.Portal.Extensions;
using Healthware.HP3.Core.Localization.ObjectValues;
using Healthware.HP3.MVC;
using Inclub.Web.Portal.Helper;
using System.Configuration;
using Inclub.Web.Portal.Models;

namespace inClub.Web.Portal.Controllers
{
    public class CommunityController : Controller
    {
        //
        // GET: /Community/
        public ActionResult Index()
        {
            #region Page Info

            var pageInfo = Inclub.Web.Portal.BL.Shared.ReadPageInfo(this.Request.RequestContext, Inclub.Web.Portal.Helper.ThemeHelper.getCurrentThemeIdentificator(), Inclub.Web.Portal.Helper.LanguageHelper.GetLanguageFromUrl());

            this.ViewBag.PageInfo = pageInfo;

            #endregion Page Info
          

            //Ricavo i Contenuti dei Box

            var valBox1 = Inclub.Web.Portal.Helper.ContentHelper.GetBoxHomeContent("5");
            this.ViewBag.TitleBox1 = valBox1.Title;
            this.ViewBag.TestoBox1 = valBox1.FullText;

            var valBox2 = Inclub.Web.Portal.Helper.ContentHelper.GetBoxHomeContent("6");
            this.ViewBag.TitleBox2 = valBox2.Title;
            this.ViewBag.TestoBox2 = valBox2.FullText;

            var valBox3 = Inclub.Web.Portal.Helper.ContentHelper.GetBoxHomeContent("7");
            this.ViewBag.TitleBox3 = valBox3.Title;
            this.ViewBag.TestoBox3 = valBox3.FullText;

            var valBox4 = Inclub.Web.Portal.Helper.ContentHelper.GetBoxHomeContent("4");
            this.ViewBag.TitleBox4 = valBox4.Title;
            this.ViewBag.TestoBox4 = valBox4.FullText;

            var manager = new AccessService();
            var ticket = manager.GetTicket();



            Boolean isAdmin = false;
            var so = new ContentSearcher();
            so.KeySite.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.PortalSite.Id;
            so.Properties.Add("Key.Id");
            so.KeySiteArea.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.Gruppi.Id;
            so.KeyContentType.Id = Inclub.Web.Portal.Keys.ContentTypeKeys.Gruppi.Id;

            var roleMng = new ProfilingManager();
            int userID = ticket.User.Key.Id;
            ViewBag.AccessWebinar = roleMng.HasRole(new UserIdentificator(userID), Inclub.Web.Portal.Keys.RoleKeys.accWebinar2);

            if (userID > 0)
                isAdmin = roleMng.HasRole(new UserIdentificator(userID), Inclub.Web.Portal.Keys.RoleKeys.SysAdmin);

            if (!isAdmin)
            {
                so.RelatedTo.ContentUser.LoadRelationDetails = true;
                so.RelatedTo.ContentUser.KeyUser.Id = userID;

            }

            ContentManager objContentManager = new ContentManager();
            objContentManager.Cache = false;

            ContentCollection groups = objContentManager.Read(so);

            // trace
            TraceHelper.TraceEvent(pageInfo.Key);
            //return View();

            if (groups != null && groups.Any())
            {
                ViewBag.listaGruppi = String.Join(",", groups.Select(cx => cx.Key.Id.ToString()).ToArray());
                return View();
            }
            else
            {
                //se non è associato al gruppo reindirizzo alla pagina dell'elenco dei gruppi
                return Redirect(this.Url.ThemeLink(Inclub.Web.Portal.Keys.ThemeKeys.Gruppi, new LanguageIdentificator(1)) + "?nogroup=true");
            }



           
        }


        public ActionResult lastFromGroup()
        {
            var manager = new AccessService();
            var ticket = manager.GetTicket();
            Boolean isAdmin = false;
            var HPLastUpdatesList = new List<inClub.Web.Portal.Models.HPLastUpdates>();
            inClub.Web.Portal.Models.HPLastUpdates modelColl;         
            var objContentManager = new ContentManager();
            var so = new ContentSearcher();
            so.KeySite.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.PortalSite.Id;
            so.KeySiteArea.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.Gruppi.Id;
            so.KeyContentType.Id = Inclub.Web.Portal.Keys.ContentTypeKeys.Gruppi.Id;
            
            so.Properties.Add("Key.Id");
            so.Properties.Add("Key.PrimaryKey");
            so.Properties.Add("Key.IdLanguage");
            so.Properties.Add("Title");
            
            so.SortOrder = ContentGenericComparer.SortOrder.DESC;
            so.SortType = ContentGenericComparer.SortType.ByTitle;
            var roleMng = new ProfilingManager();
            int userID = ticket.User.Key.Id;
            if (userID > 0)
                isAdmin = roleMng.HasRole(new UserIdentificator(userID), Inclub.Web.Portal.Keys.RoleKeys.SysAdmin);


            if (!isAdmin)
            {
                so.RelatedTo.ContentUser.LoadRelationDetails = true;
                so.RelatedTo.ContentUser.KeyUser.Id = userID;

            }

            ContentCollection groups = objContentManager.Read(so);

            if (groups != null && groups.Any())
            {
                    foreach (ContentValue grp in groups)
                    {
                        int grpKey = grp.Key.PrimaryKey;
                
                    modelColl = new inClub.Web.Portal.Models.HPLastUpdates();
                    modelColl.GroupId = grp.Key.Id;
                    modelColl.GroupName =grp.Title;

                    so = null;
                    so = new ContentSearcher();
                    so.KeySite.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.PortalSite.Id;

                    so.Properties.Add("Title");
                    so.Properties.Add("DateCreate");
                    so.Properties.Add("DatePublish");
                    so.Properties.Add("Owner.Key.Id");
                    so.Properties.Add("Owner.Name");
                    so.Properties.Add("Owner.Surname");
                    so.Properties.Add("Owner.Title");

                    so.LoadOwnerDetails = true;
                    so.KeySiteArea.Id = Inclub.Web.Portal.Keys.SiteAreaKeys.Discussioni.Id;
                    so.KeyContentType.Id = Inclub.Web.Portal.Keys.ContentTypeKeys.Discussioni.Id;

                    so.PageNumber = 1;
                    so.PageSize = 3;

                    so.SortOrder = ContentGenericComparer.SortOrder.DESC;
                    so.SortType = ContentGenericComparer.SortType.ByData;

                    so.RelatedTo.Content.Key.PrimaryKey = objContentManager.ReadPrimaryKey(grp.Key.Id, grp.Key.IdLanguage);
                    so.RelatedTo.Content.KeyRelationType.Id = Inclub.Web.Portal.Keys.RelationTypeKeys.Discussioni;


                    objContentManager.Cache = false;

                    ContentCollection discussions = objContentManager.Read(so);
                    List<inClub.Web.Portal.Models.Discussioni> discObj = new List<inClub.Web.Portal.Models.Discussioni>();
           
                    if (discussions != null && discussions.Any())
                    {

                        discObj = discussions.Select(toDiscussione).ToList();
                        //discObj.ToList().ForEach(c => { (c.GroupKey = new ContentIdentificator()).Id = grp.Key.Id; (c.GroupKey = new ContentIdentificator()).IdLanguage = grp.Key.IdLanguage; });
                        
                        discObj.ToList().ForEach(c => (c.GroupKey = new ContentIdentificator()).IdLanguage = grp.Key.IdLanguage);
                        discObj.ToList().ForEach(c => (c.GroupKey = new ContentIdentificator()).Id = grp.Key.Id);

                        modelColl.LastDiscussionsList = discObj;

                        inClub.Web.Portal.Models.Contributo comm;
                        List<inClub.Web.Portal.Models.Contributo> commList = new List<inClub.Web.Portal.Models.Contributo>();

                        string connStr = ConfigurationManager.AppSettings["conn-string"];
                        string spRead = "proc_ReadLastComment";
                        SqlDataAdapter adapter = new SqlDataAdapter();
                        DataSet ds = new DataSet();
                        using (SqlConnection sqlConn = new SqlConnection(connStr))
                        {
                            using (SqlCommand sqlCmd = new SqlCommand(spRead, sqlConn))
                            {
                                sqlConn.Open();
                                sqlCmd.Connection = sqlConn;
                                sqlCmd.CommandType = System.Data.CommandType.StoredProcedure;

                                List<SqlParameter> sqlParams = new List<SqlParameter>();
                                sqlParams.Clear();
                                sqlParams.Add(new SqlParameter("@group_id", grpKey));

                                sqlCmd.Parameters.AddRange(sqlParams.ToArray());

                                adapter.SelectCommand = sqlCmd;
                                adapter.Fill(ds);

                                if ((ds != null) && (ds.Tables != null) && (ds.Tables.Count > 0))
                                {
                                    DataTable dt = ds.Tables[0];
                                    if ((dt.Rows != null) && (dt.Rows.Count > 0))
                                    {
                                        foreach (DataRow dr in dt.Rows)
                                        {

                                            comm = new inClub.Web.Portal.Models.Contributo();
                                            comm.PostKey = new CommentIdentificator();

inClub.Web/Portal/Views/Community/Index.cshtml
@using Inclub.Web.Portal.Keys
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@using Inclub.Web.Portal.Models

@{
    //var model = new UserLogIn();
    //bool regWebinar = ViewBag.regWebinar;
    //model.webinar = regWebinar;
    //bool noWebinar = ViewBag.noWebinar;

    DateTime webinarStart = DateTime.Parse("07/11/2017 15:20");
    DateTime webinarEnd = DateTime.Parse("07/11/2017 17:30");
    DateTime orario = System.DateTime.Now;
}

                                
   @{this.Html.RenderAction("lastFromGroup");}
                

<section>

    @*<a href="javascript:void(0);" class="JOpenColorbox" onclick="javascript: leaveSite('http://www.healthwareinternational.com/events/gfk-digital-health-2017-519?k=1&j=2');">Sito Esterno</a>*@
    
    <div class="hpBox noSpaceTop">
        <div class="container">
            <div class="box5">
                <div class="left">
                    <div class="swiperEvidenza">

                        <div class="titleRed">@*<span>5</span>*@<h4>@Html.Raw(this.ViewBag.TitleBox1.ToString())</h4><a name="webinar">&nbsp;</a></div>
                        <div class="swiper-container">
                            <div class="swiper-wrapper">



                                @if (orario < webinarEnd)
                                {
                                    <div class="swiper-slide">



                                        <div class="cover"><img src="/Portal/Content/_slice/slider_webinar2.png" alt="SAVE THE DATE!"></div>
                                        <div class="cnt">
                                            <h4 class="catWeb">WEBINAR:</h4>
                                            <h3 class="webTitle">SAVE THE DATE!<br />7 Novembre<br />Ore 15:30 - 17:30</h3>
                                            <p>
                                                Approfondiscono il tema:<br />
                                                Dott.ssa Concetta Irace,<br />
                                                Dott.ssa Elena Gamarra.<br />
                                            </p>
                                            @if (ViewBag.AccessWebinar == false)
                                            {
                                                <span id="lblRegWebinar"><a href="javascript:void(0);" id="regWebinar" data-href="@Html.Raw(Url.Action("RegistraWebinar", "Community"))" class="readMore readWebinar">Registrati <i class="fa fa-arrow-right" aria-hidden="true"></i></a></span>
                                            }
                                            else
                                            {
                                                if (orario < webinarStart)
                                                {
                                                    <h4 id="msg_iscritto">Sei iscritto al webinar</h4>
                                                }
                                                else
                                                {
                                                    <a href="https://zoom.us/j/881106350" class="readMore highlight" target="_blank">Clicca qui per accedere al webinar</a>
                                                }
                                            }
                                        </div>

                                    </div>
                                }
                                else
                                {
                                    <style>
                                        .swiperEvidenza .swiper-pagination {
                                            display: none;
                                        }

                                        .swiperEvidenza .swiper-button-next {
                                            display: none;
                                        }

                                        .swiperEvidenza .swiper-button-prev {
                                            display: none;
                                        }
                                    </style>
                                }

                                @Html.Raw(this.ViewBag.TestoBox1.ToString())
                            </div>
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                    @*<div class="incontraBox JSdoLogin">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <h4>Incontra nuovi membri della tua community</h4>
                            <a href="javascript:void(0);" title="Read more" class="readMore"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                        </div>*@
                    @*<div class="rocheBox">
                            <img src="/Portal/Content/_slice/roche.png" alt="Roche" />
                            <h4>Visita il sito web di Roche</h4>
                            <a href="#" title="Read more" class="readMore"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                        </div>*@
                </div>
            </div>

            

            

            <div class="box3">
                <div class="right">
                    <div class="swiperVideo" style="display:none;">
                        <div class="titleRed JSdoLogin">@*<span>3</span>*@<h4>@Html.Raw(this.ViewBag.TitleBox2.ToString())</h4></div>
                        <div class="swiper-container">
                           @* @Html.Raw(this.ViewBag.TestoBox2.ToString())*@
                            @{ Html.RenderAction("LastVideos", "Community", new { groupsList = ViewBag.listaGruppi, langId = 1, altText = @Html.Raw(this.ViewBag.TestoBox2.ToString()) }); }
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                    <div class="swiperNews">
                        <div class="titleRed JSdoLogin">@*<span>2</span>*@<h4>@Html.Raw(this.ViewBag.TitleBox3.ToString())</h4></div>
                        <div class="swiper-container">
                            @*@Html.Raw(this.ViewBag.TestoBox3.ToString())*@
                            @{ Html.RenderAction("LastNews", "Community", new { langId = 1, altText = @Html.Raw(this.ViewBag.TestoBox3.ToString()) }); }
                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>
                </div>
            </div>

            <div class="swiperGeneric externalSwiper">
                <div class="titleTransparent"><div class="swiper-pagination"></div></div>
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        @Html.Raw(this.ViewBag.TestoBox4.ToString())
                    </div>
                </div>

                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
        </div>
    </div>

</section>
<script>

    $(function () {

        var hash = window.location.hash.substring(1); //Puts hash in variable, and removes the # character
        if (hash == "webinar") {
            $("#msg_iscritto").addClass("highlight");
        }

        $("#regWebinar").click(function (e) {
            if (confirm("Procedere all'iscrizione al webinar?") == true) {
                $.ajax({
                    type: "POST",
                    url: "/Community/RegistraWebinar",
                    success: function (data) {
                        if (data == "ok") {
                            alert("Iscrizione avvenuta con successo!");
                            $("#lblRegWebinar").html('<h4>Sei iscritto al webinar</h4>');
                        } else {
                            alert(data);
                        }
                    },

                    error: function (errorData) {
                        //onError(errorData);
                    }

                });
            }
        });

    });

</script>


<script type="text/javascript">


    $(document).ready(function () {

      //  LoadLastUpdates(2);

    });



    function LoadLastUpdates(groupID) {
        //alert('LoadLastUpdates:' + groupID)
     
        $.ajax({
            type: "GET",
            url: "/Community/lastFromGroup",
            data: { groupId: groupID },
            success: function (data) {                

                $("#sliderLastUpd").append(data); 

            },

            error: function (errorData) {
                //onError(errorData);
            }

        });
    }

</script>

inClub.Web/Portal/Views/Community/_ProponiGruppo.cshtml
@model Inclub.Web.Portal.Models.ProponiGruppo
@using Inclub.Web.Portal.Keys
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@{
    Layout = "~/portal/Views/Shared/_LayoutPopup.cshtml";   
    
}


<section>
    <div class="registerBox">
        <div class="container containerPopup500">
            <div class="box8">
                <div class="cntRegister">
                    <div class="box6">
                        <h3>@Html.Raw(DictionaryHelper.GetLabel(DictionaryKeys.GruppiTitleProponi, LabelKeys.LANGUAGE_PORTAL))</h3>
                        <p class="textPopup">@Html.Raw(DictionaryHelper.GetLabel(DictionaryKeys.GruppiTextProponi, LabelKeys.LANGUAGE_PORTAL))</p>
             @using (Ajax.BeginForm("ProponiGruppo", "Community", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "result", OnFailure = "jsOnFailure();", OnSuccess = "jsOnSuccess();", InsertionMode = InsertionMode.Replace }, new { id = "ActionForm" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.AntiForgeryToken()
                                <div class="JChangeOk">
                                    <div class="rowForm JChangeOk">
                                        <div class="box4">@this.Html.TextBoxFor(m => m.Title, new { placeholder = "Titolo" })</div>
                                    </div>

                                    <div class="rowForm JChangeOk">
                                        <div class="box4">@this.Html.TextAreaFor(m => m.Description, new { placeholder = "Descrizione" })</div>
                                    </div>


                                    <div class="rowForm  JChangeOk">
                                        <div id="result" style="display:none;color:red; font-size:12px;"></div>
                                    </div>
                                    <div class="rowForm checkRow JChangeOk">
                                        <div class="box2">
                                            <a href="javascript:void(0);" title="Invia" class="btn" id="JSsend">Invia</a>
                                        </div>
                                    </div>
                                </div>
                        }


                    <div class="rowForm checkRow JsResultOk" style="display:none; margin:0;">
                        <div class="box2">
                            Il nuovo gruppo è stato inviato in approvazione.
                        </div>
                    </div>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>



<script>

    $(document).ajaxComplete(function () {
        $.validator.unobtrusive.parse('Form');
    });

    /*SCRIPT per FORM*/
    $(function () {

        $("#JSsend").click(function (e) {
            e.preventDefault();
            $('form#ActionForm').submit();
        });

    });

    function jsOnFailure() {
        alert("Error");
    }

    function jsOnSuccess() {
        if ($('#Title').val() != '')
        {
            $(".JsResultOk").fadeIn();
            $(".JChangeOk").hide();
            $(".textPopup").hide();            
        }
        else
        { $("#result").fadeIn(); }
    }

    
</script>

inClub.Web/Portal/Views/Community/lastFromGroup.cshtml
@model List<inClub.Web.Portal.Models.HPLastUpdates>
@using Inclub.Web.Portal.Keys
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@using Healthware.HP3.Core.Site.ObjectValues
@using Healthware.HP3.Core.Localization.ObjectValues
@using Healthware.HP3.Core.Content.ObjectValues
@using Healthware.HP3.Core.Utility


@if (this.Model != null && this.Model.Any())
{
    var _currGroupDetail = string.Empty;
    <section>
        <div class="hpBox noSpaceBottom">
            <div class="container">
                <div class="box12">
                    <div class="right">
                        <div class="swiperLastUpd swiperLastGroups">
                            <div class="titleRed JSdoLogin"><h4>Ultime dai miei gruppi</h4></div>
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                   
                                    @foreach (var item in this.Model)
                                    {
                                        _currGroupDetail = this.Url.ThemeLinkDetail(ThemeKeys.HPGruppo, new ContentIdentificator(item.GroupId, 1), new LanguageIdentificator(1), item.GroupName, "detail");

                                        <div class="swiper-slide">
                                            <h2 class="nomeGroups"><a href="@_currGroupDetail">@item.GroupName</a></h2>
                                            <div class="box4">
                                                <h3 class="bgtitle">ULTIME DISCUSSIONI</h3>
                                                @if (item.LastDiscussionsList != null && item.LastDiscussionsList.Any())
                                                {
                                                    var _currDiscDetail = string.Empty;

                                                    foreach (inClub.Web.Portal.Models.Discussioni disc in item.LastDiscussionsList)
                                                    {

                                                        _currDiscDetail = this.Url.ThemeLinkDetail(ThemeKeys.HPGruppo, new ContentIdentificator(disc.GroupKey.Id, disc.GroupKey.IdLanguage), new LanguageIdentificator(disc.GroupKey.IdLanguage), disc.Title, "detail", disc.DiscussionKey.Id.ToString(), "discussioni");

                                                        <div class="commlats">
                                                            <h3><a href="@_currDiscDetail" title="@disc.Title">@disc.Title</a></h3>
                                                            <div class="author"><h4>di <span>@disc.UserCreateName</span></h4></div>
                                                        </div>
                                                    }
                                                }
                                            </div>
                                            <div class="box4">
                                                <h3 class="bgtitle">ULTIMI CONTRIBUTI</h3>
                                                @if (item.LastPostsList != null && item.LastPostsList.Any())
                                                {
                                                    var _currPostDetail = string.Empty;
                                                    foreach (inClub.Web.Portal.Models.Contributo post in item.LastPostsList)
                                                    {
                                                        _currPostDetail = this.Url.ThemeLinkDetail(Inclub.Web.Portal.Keys.ThemeKeys.HPGruppo, new ContentIdentificator(post.GroupKey.Id, post.GroupKey.IdLanguage), new LanguageIdentificator(post.GroupKey.IdLanguage), post.DiscussionTitle, "detail", post.DiscussionKey.Id.ToString(), "discussioni") + "&p=" + SimpleHash.UrlEncryptRijndaelAdvanced(post.FatherID.ToString()) + "&c=" + SimpleHash.UrlEncryptRijndaelAdvanced(post.PostKey.Id.ToString());
                                                        <div class="commlats">
                                                            <div class="lxlate">
                                                                <a href="@_currPostDetail" title="@post.Description">
                                                                    <img src="@post.UserCover" alt="@post.UserCreateName" />
                                                                </a>
                                                            </div>
                                                            <div class="rxlate">
                                                                <h3><a href="@_currPostDetail" title="@post.Description">                                                                    
                                                                    @(post.Description.Length > 150 ? post.Description.Substring(0, 145) + "..." : post.Description) 
                                                                    </a></h3>
                                                                <h4>di <span>@post.UserCreateName</span></h4>
                                                                <h4>in <a href="@_currPostDetail" title="@post.Description">@post.DiscussionTitle</a></h4>
                                                            </div>
                                                        </div>
                                                    }
                                                }
                                            </div>
                                        </div>

                                    }



                                    @*<div id="sliderLastUpd"></div>*@
                                </div>
                            </div>
                            <div class="swiper-pagination"></div>
                            <div class="swiper-button-next"></div>
                            <div class="swiper-button-prev"></div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </section>
}

inClub.Web/Portal/Views/Community/lastNews.cshtml
@model  IEnumerable<Inclub.Web.Portal.Models.GenericContentArchives>
@using Inclub.Web.Portal.Keys
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@using Healthware.HP3.Core.Site.ObjectValues
@using Healthware.HP3.Core.Localization.ObjectValues
@using Healthware.HP3.Core.Content.ObjectValues
@using Healthware.HP3.Core.Utility


@if (this.Model != null && this.Model.Any())
{
    var _currDetail = string.Empty;
    <div class="swiper-wrapper">

        @foreach (var item in this.Model)
        {
            _currDetail = this.Url.ThemeLinkIndex(new Healthware.HP3.Core.Site.ObjectValues.ThemeIdentificator(@item.ThemeId), @item.Key, @item.Title);
            var imgCover = "/hp3image/cover/" + Inclub.Web.Portal.Helper.CoverHelper.getCover(new Healthware.HP3.Core.Content.ObjectValues.ContentIdentificator(item.Key.Id, (short)item.LanguageId), (int)EnumeratorKeys.coverDimension.NewsWidthArchive, (int)EnumeratorKeys.coverDimension.NewsHeightArchive, Inclub.Web.Portal.Keys.EnumeratorKeys.coverPosition.third);
            <div class="swiper-slide">
                <img src="@imgCover" alt="@item.Title" />
                <h3>@item.Title</h3>
                <a href="@_currDetail" title="Read more" class="readMore"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
            </div>

        }

    </div>
               
}

   