inClub.Web/Portal/Controllers/RegistrazioneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;
using System.Drawing.Imaging;
using System.Web.Mvc;
using Inclub.Web.Portal.Helper;
using Inclub.Web.Portal.BL;
using System.Text.RegularExpressions;
using Inclub.Web.Portal.Keys;
using Inclub.Web.Portal.Models;
using Healthware.HP3.Core.Site.ObjectValues;
using Healthware.HP3.Core.User.ObjectValues;
using Healthware.HP3.MVC;
using Healthware.HP3.Core.User;
using Healthware.HP3.Core.Utility;
using System.IO;

namespace Inclub.Web.Portal.Controllers
{
    public class RegistrazioneController : Controller
    {
        //
        // GET: /Registrazione/

        public ActionResult Index()
        {
            #region Page Info
            var pageInfo = Shared.ReadPageInfo(this.Request.RequestContext, ThemeHelper.getCurrentThemeIdentificator());
            this.ViewBag.PageInfo = pageInfo;
            #endregion Page Info

            //check sul codice, lo decripto, se è ok faccio compilare il form sennò lo reindirizzo di nuovo su accesscode
            string accessCode = "";
            accessCode = ((Request["ac"]!= null) ? SimpleHash.UrlDecryptRijndaelAdvanced(Request["ac"].ToString()) : "");

            //codice commentato per non esseree reindirizzati alla pagina del codice quando si vuole accedere al form di registrazione, decommentare se non si vuole far registrare qualsiasi utente
            if ((accessCode == "") || (!GenericHelper.checkAccessCode(accessCode)))
                return new RedirectResult(LinkHelper.ThemeLink(this.ControllerContext, ThemeKeys.AccessCode) + "?nac=true");


            if (UserHelper.getUserLoggedId() > 0)
            {
                return new RedirectResult(LinkHelper.ThemeLink(this.ControllerContext, ThemeKeys.ModificaDati));
            }

            //trace            
            TraceHelper.TraceEvent(pageInfo.Key);

            UserRegistration model = new UserRegistration();
            model.AcceptNotify = true;
            model.TermsAndConditions = true;
            model.AccessCode = accessCode;
            InitViewData(ref model);

            
            //se no o reindirizzo a accesscode o stampo un messaggio con link ad accesscode
            //se sì lo metto in un campo nascosto che poi passo al metodo per salvare l'utente, a buon esisto della registrazione flaggo il codice come utilizzato

            return View(model);
        }

        private void InitViewData(ref UserRegistration model)
        {
            var so = new ContextSearcher();
            so = new ContextSearcher();
            so.KeyContextGroup = ContextGroupKeys.SpecializzazioniRegistrationForm;
            List<SelectListItem> specItems = ContextHelper.GetContexts(so, "");
            model.Specializzazioni = new SelectList(specItems, "Value", "Text");
            so = null;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UserRegistration model, HttpPostedFileBase file)
        {
            #region Page Info
            var pageInfo = Shared.ReadPageInfo(this.Request.RequestContext, ThemeHelper.getCurrentThemeIdentificator());
            this.ViewBag.PageInfo = pageInfo;
            #endregion Page Info

            Inclub.Web.Portal.Models.OperationResult operationResult = new Inclub.Web.Portal.Models.OperationResult();
            operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Failed;

            InitViewData(ref model);

            if (ModelState.ContainsKey("FirstName"))
                ModelState["FirstName"].Errors.Clear();
            if (ModelState.ContainsKey("LastName"))
                ModelState["LastName"].Errors.Clear();
            if (ModelState.ContainsKey("AcceptInfo"))
                ModelState["AcceptInfo"].Errors.Clear();


            if (ModelState.IsValid)
            {

                var captchaValid = false;
                try
                {
                    captchaValid = CaptchaGeneratorHelper.Validate(this.HttpContext, CaptchaKeys.RegistrationForm, model.Captcha);
                    if (!captchaValid)
                    {
                        ModelState.AddModelError("Captcha", DictionaryHelper.GetLabel(DictionaryKeys.CaptchaError));

                    }
                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("Captcha", DictionaryHelper.GetLabel(DictionaryKeys.CaptchaError));
                }


                if (captchaValid)
                {


                    this.ViewBag.ShowMessage = true;
                    //registrazione

                    try
                    {
                        EnumeratorKeys.UserStatus userStatType;


                        //controllo che non esista un utente registrato con la stessa userid/email
                        userStatType = UserHelper.GetUserTypeByEmail(model.Email);
                        bool continueRegistration = true;
                        switch (userStatType)
                        {
                            case EnumeratorKeys.UserStatus.Active:
                                operationResult.Message = DictionaryHelper.GetLabel(string.Format(DictionaryKeys.regFormMsg, (int)EnumeratorKeys.UserStatus.Active));
                                operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Failed;
                                continueRegistration = false;
                                break;
                            case EnumeratorKeys.UserStatus.Pending:
                                operationResult.Message = DictionaryHelper.GetLabel(string.Format(DictionaryKeys.regFormMsg, (int)EnumeratorKeys.UserStatus.Pending));
                                operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Failed;
                                continueRegistration = false;
                                break;
                            case EnumeratorKeys.UserStatus.NoActive:
                                operationResult.Message = DictionaryHelper.GetLabel(string.Format(DictionaryKeys.regFormMsg, (int)EnumeratorKeys.UserStatus.NoActive));
                                operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Failed;
                                //Email di approvazione
                                //rimando la email per attivazione utente
                                //RemindActivationEmail(model);
                                continueRegistration = false;
                                break;
                            case EnumeratorKeys.UserStatus.Disable:
                            case EnumeratorKeys.UserStatus.NotFound:


                                if (continueRegistration)
                                {

                                    //creazione utente

                                    UsersManage objUserManage = new UsersManage();
                                    var objCreatedHCP = objUserManage.CreateNewUser(model);

                                    //Salvo L'immagine del Profilo
                                    if (null != objCreatedHCP && objCreatedHCP.Key.Id > 0)
                                    {

                                        if (file != null)
                                        {
                                            var allowedExtensions = new[] { ".Jpg", ".png", ".jpg", "gif" };
                                            var fileName = Path.GetFileName(file.FileName);

                                            var ext = Path.GetExtension(file.FileName);
                                            if (allowedExtensions.Contains(ext)) //check what type of extension  
                                            {
                                                string myfile = string.Format("{0}{1}", CryptHelper.urlEncrypt(objCreatedHCP.Key.Id.ToString()), ext);
                                                string myfile_small = string.Format("{0}_100{1}", CryptHelper.urlEncrypt(objCreatedHCP.Key.Id.ToString()), ext);
                                                var path = Path.Combine(Server.MapPath("~//HP3Image/User/cover/"), myfile);
                                                var path_small = Path.Combine(Server.MapPath("~//HP3Image/User/cover/"), myfile);



                                                //Se esiste già Elimino la cover originale
                                                if (System.IO.File.Exists(path))
                                                {
                                                    System.IO.File.Delete(path);
                                                }
                                                //Se esiste già Elimino la cover originale
                                                if (System.IO.File.Exists(path_small))
                                                {
                                                    System.IO.File.Delete(path_small);
                                                }

                                                Image myfilename = new Bitmap(file.InputStream);
                                                Image img = Image.FromStream(file.InputStream);
                                                int actualWidth_small = img.Width;
                                                int actualHeight_small = img.Height;
                                                int MaxWidth_small = LabelKeys.UserCoverWidth;
                                                if (img.Width > MaxWidth_small)
                                                {
                                                    actualWidth_small = MaxWidth_small;

                                                    int originalHeight = myfilename.Height;
                                                    int originalWidth = myfilename.Width;

inClub.Web/Portal/Views/Registrazione/_ResetPassword.cshtml
@model Inclub.Web.Portal.Models.UserResetPassword
@using Inclub.Web.Portal.Keys
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions

@{
    Layout = "~/portal/Views/Shared/_LayoutPopup.cshtml";
}


<section>
    <div class="registerBox" style="background-color:#FFF;">
        <div class="container">
            <div class="box8">
                <div class="cntRegister">                 
                    <div class="box6" style="height:450px">
                        <h3>Richiedi Password</h3>

                        @using (Ajax.BeginForm("ResetPassword", "Registrazione", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "resultResetPassword", OnFailure = "jsOnFailureResetPsw();", OnSuccess = "$('#resultResetPassword').fadeIn();", InsertionMode = InsertionMode.Replace }, new { id = "ResetPasswordForm" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.AntiForgeryToken()

    <p class="textPopup">
        @Html.Raw(DictionaryHelper.GetLabel(DictionaryKeys.ResetPasswordLaunch, LabelKeys.LANGUAGE_PORTAL))       
    </p>
                            <div class="rowForm JChangeOk">
                                <div class="box4">@this.Html.TextBoxFor(m => m.Email, null, new { @maxlength = "200",placeholder = "Email" })</div>
                            </div>


    <div class="rowForm JChangeOk">
        <div class="box4 captchaRow"><img src="@Url.Action("Get", "Captcha", new{ name=CaptchaKeys.RegistrationForm})" class="jsCaptcha captcha" alt="captcha" /> @Html.TextBoxFor(m => m.Captcha, new { @class = "TypeCaptchaPopup", placeholder = "Captcha" }) <a href="javascript:void(0);" class="jsReloadCaptcha" title="Ricarica il codice Captcha"><img src="@Url.Content("~/portal/Content/_slice/reload.png")" alt="codice Captcha" title="Ricarica il codice Captcha" width="30" class="ReloadCaptcha" /></a></div>

    </div>


                            <div class="rowForm  JChangeOk">
                                <div id="resultResetPassword" style="display:none;color:red; font-size:12px;"></div>
                                </div>
                            <div class="rowForm checkRow JChangeOk" style="width:205px;">
                                <div class="box2">
                                    <a href="javascript:void(0);" title="Invia Richiesta" class="btn" id="JResetPassword">Invia Richiesta</a>
                                </div>
                            </div>  
                        }


                        <div class="rowForm checkRow JsResultOk" style="display:none; height:350px;">
                            <div class="box2">
                                Le indicazioni per recuperare la password le sono state inviate al suo account di posta elettronica
                            </div>

                            <div class="rowForm checkRow" style="width:180px;">
                                <div class="box2">
                                    <a href="javascript:void(0);" title="Chiudi" class="btn JCloseColorbox" id="CloseColorbox">Chiudi</a>
                                </div>
                            </div>  

                        </div>                        

                    </div>
                    <div class="box1">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</section>



<script>

    $(document).ajaxComplete(function () {
        $.validator.unobtrusive.parse('Form');
    });

   

    function initResetForm() {
      

        $(".jsReloadCaptcha").click(function (e) {
            $(".jsCaptcha").hide();

            $.ajax({
                url: '@this.Url.Action("Regenerate", "Captcha")',
                dataType: 'json',
                type: 'POST',
                data: { name: '@CaptchaKeys.RegistrationForm' },
                success: function (data) {
                    if (true == data) {
                        var captchaUrl = '@this.Url.Action("Get", "Captcha", new{name = CaptchaKeys.RegistrationForm})&t=' + new Date().getTime();
                        $('.jsCaptcha').attr('src', captchaUrl)
                                .show();
                    }
                }
            });

            e.preventDefault();
        });
    };




    /*SCRIPT per FORM*/
    $(function () {

        $("#JResetPassword").click(function (e) {
            e.preventDefault();
            $('form#ResetPasswordForm').submit();
        });        
        /*SCRIPT per FORM*/

        initResetForm();
        $(".jsReloadCaptcha").click();
   



    });

    function jsOnFailureResetPsw() {
        alert("Error");
    }


</script>

inClub.Web/Portal/Views/Registrazione/_ResetPasswordOK.cshtml
@using Inclub.Web.Portal.Helper;
@{  
    var msg = this.Html.GetLabel(Inclub.Web.Portal.Keys.DictionaryKeys.UpdateOk, Inclub.Web.Portal.Keys.LabelKeys.LANGUAGE_PORTAL); 
  

    }

@Styles.Render("~/Style/css")
@Scripts.Render("~/Scripts/js")

<div id="resultResetPassword">Le indicazioni per recuperare la password le sono state inviate al suo account di posta elettronica</div>
<script>
    $(function () {
        $(".JChangeOk").hide();
        $(".JsResultOk").show();
    });
</script>