inClub.Web/Portal/Controllers/ContattiController.cs
using Healthware.HP3.MVC.Attributes;
using Inclub.Web.Portal.Keys;
using Inclub.Web.Portal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Healthware.HP3.Core.User;
using Healthware.HP3.Core.User.ObjectValues;

namespace Inclub.Web.Portal.Controllers
{
    public class ContattiController : Controller
    {
        //
        // GET: /ContactUs/

        public ActionResult Index()
        {

            ContactUs modelcontact = new ContactUs();


            #region Page Info
            var pageInfo = BL.Shared.ReadPageInfo(this.Request.RequestContext, Helper.ThemeHelper.getCurrentThemeIdentificator());
            this.ViewBag.PageInfo = pageInfo;
            #endregion Page Info

            var manager = new AccessService();
            var Userticket = manager.GetTicket();
            if  (Userticket.User.Key.Id>0)
            {

                //IDictionary<string, object> atts = new Dictionary<string, object>();
                //atts.Add("class", "UserField");

                //atts.Add("readonly", "readonly");
               

                UserValue user = new UserValue();
                user = Inclub.Web.Portal.Helper.UserHelper.GetUserBaseValueByUserId(Userticket.User.Key.Id);
                modelcontact.Name = user.Name;
                modelcontact.Surname = user.Surname;
                modelcontact.Email = user.Email.GetString;
               

                //HtmlAttributeDict = atts;
               


                return View(modelcontact);
            }

            //trace
            //Helper.TraceHelper.TraceEvent(pageInfo.Key);
            return View();
        }

        [HttpPost]
        [AjaxOnly]
        [ValidateInput(true)]
        [ValidateAntiForgeryToken]
        public ActionResult SendContact(ContactUs model)
        {
            var captchaValid = false;
            string _span = "<p  class='errorTxt'>{0}</p>";
            var result = new OperationResult() { Successful = false };

            captchaValid = Helper.CaptchaGeneratorHelper.Validate(this.HttpContext, Keys.CaptchaKeys.ContactUseForm, model.Captcha);
            if (!captchaValid)
            {
                ModelState.AddModelError("Captcha", string.Format(_span, Helper.DictionaryHelper.GetLabel(Keys.DictionaryKeys.CaptchaError)));
                result.Successful = false;
                result.StatusCode = 5;
                result.Message = "<p  class='errorTxt'>Codice Capcha Errato</p>"; 
                return Json(result, JsonRequestBehavior.DenyGet);
            }

            if (ModelState.IsValid && captchaValid)
            {                         
                   
                    try
                    {

                         //SendMail
                        SendMail(model);
                        result.Successful = true;
                        result.Message = String.Format("<p>{0}</p>",Helper.DictionaryHelper.GetLabel(Keys.DictionaryKeys.SendContactUsSuccessfully,Keys.LabelKeys.LANGUAGE_PORTAL));
                        Helper.TraceHelper.TraceEvent(ThemeKeys.Contatti, TraceEventKeys.SendContactUs);
                    }
                    catch (Exception ex)
                    {
                        result.Message = String.Format("<p>{0}</p>", Helper.DictionaryHelper.GetLabel(Keys.DictionaryKeys.GenericError, Keys.LabelKeys.LANGUAGE_PORTAL));
                        result.StatusCode = (int)Keys.EnumeratorKeys.StatusCode.Error;
                        Helper.ErrorLogHelper.NotifyDBLog(ex, "");
                    }
                
            }
            else
            {

                //SendMail
              
                result.Successful = false;
                result.StatusCode = 5;
                result.Message = "<p  class='errorTxt'>Tutti i campi sono obbligatori</p>"; 

            }
               // return Json(string.Format(_span, Helper.DictionaryHelper.GetLabel(Keys.DictionaryKeys.CaptchaError, LabelKeys.LANGUAGE_PORTAL)));

            return Json(result, JsonRequestBehavior.DenyGet);
        }


        #region Private

        private void SendMail(ContactUs model)
        {
            string htmlTemplate = Helper.DictionaryHelper.GetLabel(Keys.DictionaryKeys.htmlMailTemplate, Keys.LabelKeys.LANGUAGE_PORTAL);
            Dictionary<string, string> replacing = new Dictionary<string, string>();
            replacing.Add(Keys.LabelKeys.em_NAME, model.Name);
            replacing.Add(Keys.LabelKeys.em_SURNAME, model.Surname);    
            replacing.Add(Keys.LabelKeys.em_SUBJECT, model.Subject);
            replacing.Add(Keys.LabelKeys.em_EMAIL, model.Email);
            replacing.Add(Keys.LabelKeys.em_MESSAGE, model.MessageBody);
            int langId = Keys.LabelKeys.LANGUAGE_PORTAL;
            Helper.MailHelper.SendMail(MailTemplateKeys.ContactUs, langId, htmlTemplate, replacing, false, "");

        }

      
        #endregion
    }
}

inClub.Web/Portal/Views/Contatti/Index.cshtml
@model Inclub.Web.Portal.Models.ContactUs
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@{

    Layout = "~/portal/Views/Shared/_LayoutEmpty.cshtml";

    var PageInfo = this.ViewBag.PageInfo as Inclub.Web.Portal.Models.PageInfo;
}
<section>
    <div class="registerBox">
        <a href="/" class="back" title="Back">&lt; Back</a>
        <div class="container">
            <div class="box8">
                <div class="cntRegister">
                    <div class="pageTitleTop">
                        <div class="box1">&nbsp;</div>
                        <div class="box6">
                            <h1>@PageInfo.AreaTitle</h1>
                            <div class="internalMessage" id="divLaunch">
                                @PageInfo.Launch
                            </div>
                        </div><div class="box1">&nbsp;</div>
                    </div>




                    <div class="box1">&nbsp;</div>
                    <div class="box6">
                       

                        @using (Ajax.BeginForm("SendContact", "contatti", null, new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "jsresultContact", OnFailure = "jsOnFailure();", InsertionMode = InsertionMode.Replace }, new { id = "contactform", @class = "JsContactForm form-box register-form form-validator contact-form" }))
                        {
                            @Html.ValidationSummary(true)
                            @(this.Html.AntiForgeryToken())

   
                            @*@Html.Raw(DictionaryHelper.GetLabel(DictionaryKeys.ContactPage))*@


    <div class="jsContainerForm">

        <h3><span>I campi contrassegnati da asterisco (*) sono obbligatori.</span></h3>
        <div class="rowForm">
            <div class="box2">Oggetto*</div>
            <div class="box4">
                @Html.TextBoxFor(c => c.Subject, new
                                                   {
                                                       tabindex = 1,
                                                       @class = "JsClearFields",
                                                       maxlength = "200"
                                                   })
            </div>
            <div class="box2 errorTxt"><span class="jsOggetto" style="display:none;">Campo Obbligatorio</span></div>
        </div>





        <div class="rowForm">
            <div class="box2">Nome*</div>
            <div class="box4">
                @Html.TextBoxFor(c => c.Name, new
                                        {
                                            tabindex = 2,
                                            @class = "JsClearFields UserField",
                                            maxlength = "200"

                                        })
            </div>
            <div class="box2 errorTxt"><span class="jsName" style="display:none;">Campo Obbligatorio</span></div>
        </div>


        <div class="rowForm">
            <div class="box2">Cognome*</div>
            <div class="box4">
                @Html.TextBoxFor(c => c.Surname, new
                                        {
                                            tabindex = 3,
                                            @class = "JsClearFields",
                                            maxlength = "200"
                                        })
            </div>
            <div class="box2 errorTxt"><span class="jsSurname" style="display:none;">Campo Obbligatorio</span></div>
        </div>


        <div class="rowForm">
            <div class="box2">Email*</div>
            <div class="box4">
                @Html.TextBoxFor(c => c.Email, new
                                    {
                                        tabindex = 5,
                                        type = "email",
                                        @class = "JsClearFields",
                                        maxlength = "250"
                                    })
            </div>
            <div class="box2 errorTxt">@this.Html.ValidationMessageFor(c => c.Email, null, new { @class = "required" })</div>
            <div class="box2 errorTxt"><span class="jsEmail" style="display:none;">Campo Obbligatorio</span></div>
            <div class="box2 errorTxt"><span class="jsEmailFormat" style="display:none;">Formato Email non corretto</span></div>
        </div>


        <div class="rowForm">
            <div class="box2">Captcha*</div>
            <div class="box4 captchaRow"><img src="@Url.Action("Get", "Captcha", new{ name=CaptchaKeys.RegistrationForm})" class="jsCaptcha captcha" alt="captcha" /> @Html.TextBoxFor(c => c.Captcha, new { @class = "JsClearFields TypeCaptcha" }) <a href="javascript:void(0);" class="jsReloadCaptcha" title="Ricarica il codice Captcha"><img src="@Url.Content("~/portal/Content/_slice/reload.png")" alt="codice Captcha" title="Ricarica il codice Captcha" width="30" class="ReloadCaptcha" /></a></div>
            <div class="box2 errorTxt">
                                           <span class="jsCaptchaError" style="display:none;">Campo Obbligatorio</span>
                                           <span id="jsresultContactCaptcha" class="jsresultContactCaptcha title-case-message"></span>
                
                </div>
        </div>


        <div class="rowForm">
            <div class="box2">Messaggio*</div>
            <div class="box4">
                @Html.TextAreaFor(c => c.MessageBody, new
                                    {
                                        tabindex = 7,
                                        @class = "JsClearFields ContactUstextarea",
                                        maxlength = "500"
                                    })
            </div>
            <div class="box2 errorTxt"><span class="jsMessaggio" style="display:none;">Campo Obbligatorio</span></div>
        </div>


        <div class="rowForm">Presa visione dell'<a href="/Informativa-Trattamento-Dati" target="_blank">Informativa sul trattamento dei dati</a> e dell’<a href="/avvertenza-di-rischio" target="_blank">avvertenza di rischio</a> acconsento al trattamento dei dati personali, all'eventuale comunicazione ai soggetti elencati nell'informativa per le finalità e con le modalità indicate e al trasferimento all'estero, anche in paesi non appartenenti all'Unione Europea.</div>

        <div class="rowForm checkRow">
            <div class="box2">&nbsp;</div>
            <div class="box4"><a href="javascript:void(0);" title="Registrati" id="jsSubmit" class="btn jsSubmit">Invia</a></div>
            <div class="box2">&nbsp;</div>
        </div>

    </div>


                                <div class="rowForm generic">

                                    <div id="jsresultContact" class="jsresultContact title-case-message"></div>

                                </div>
                           
                        }


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section JSscripts
{
    <script src="~/Portal/Content/js/Views/Contatti.js"></script>
    <script type="text/javascript">
        $(function () {
            var ContactUsLogic = Portal.ContactUs({
                actions: {
                    url: '@this.Url.Action("SendContact", "Contatti")',
                },
                FormClass: '.JsContactForm',
                ClearClass: '.JsClearFields'
            });




            $(".jsReloadCaptcha").click(function (e) {
                $(".jsCaptcha").hide();

                $.ajax({
                    url: '@this.Url.Action("Regenerate", "Captcha")',
                    dataType: 'json',
                    type: 'POST',
                    data: { name: '@CaptchaKeys.ContactUseForm' },
                    success: function (data) {
                        if (true == data) {
                            var captchaUrl = '@this.Url.Action("Get", "Captcha", new { name = CaptchaKeys.ContactUseForm })&t=' + new Date().getTime();
                            $('.jsCaptcha').attr('src', captchaUrl)
                                    .show();


                        }
                    }
                });

                e.preventDefault();

            });

            $(".jsReloadCaptcha").click();
        });


    </script>
}