inClub.Web/Portal/Controllers/RecuperaPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Healthware.HP3.Core.User;
using Healthware.HP3.Core.User.ObjectValues;
using Healthware.HP3.MVC.Attributes;

using Inclub.Web.Portal.Keys;
using Inclub.Web.Portal.Models;
using Inclub.Web.Portal.Helper;
using Inclub.Web.Portal.BL;

namespace Inclub.Web.Portal.Controllers
{
    public class RecuperaPasswordController : Controller
    {
        //
        // GET: /RecuperaPassword/

        public ActionResult Index(int? ok)
        {
            UserResetPasswordForm model = new UserResetPasswordForm();
              model.Id = 0;
            #region Page Info
            var pageInfo = BL.Shared.ReadPageInfo(this.Request.RequestContext, Helper.ThemeHelper.getCurrentThemeIdentificator());
            this.ViewBag.PageInfo = pageInfo;
            #endregion Page Info
            
            //in modo da tracciare solo quando arrivo alla pagina e non quando ho effettuato il cambio password
            if ((!ok.HasValue) || (ok.Value != 1))
            {
                //trace
                Helper.TraceHelper.TraceEvent(pageInfo.Key);
                int userID = 0;

                if (Request.QueryString[LabelKeys.UserIdSL_Generic] != null)
                { 

                int.TryParse( CryptHelper.urlDecrypt(Request.QueryString[LabelKeys.UserIdSL_Generic]), out userID);
                if (userID > 0)
                {
                    model.Id = userID;
                    return View(model);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return View("_IndexOK");
            }
        }

        [HttpPost]
        public ActionResult ResetPassword(UserResetPasswordForm model)
        {
            Inclub.Web.Portal.Models.OperationResult operationResult = new Inclub.Web.Portal.Models.OperationResult();
            operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Failed;

            if (ModelState.IsValid)
            {
                if (model.Id>0)
                {
                    UsersManage manager = new UsersManage();
                    manager.UpdateHCPResetPassword(model.Id, model.Password);
                    Helper.TraceHelper.TraceEvent(Keys.ThemeKeys.RecuperaPassword, Keys.TraceEventKeys.ChangePassword);
                    operationResult.StatusCode = (int)EnumeratorKeys.StatusCode.Succeded;
                    operationResult = null;
                    return new RedirectResult(string.Format("{0}?ok={1}", Helper.LinkHelper.ThemeLink(this.ControllerContext, Keys.ThemeKeys.RecuperaPassword), 1));
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            else
            {
           
                Helper.ErrorLogHelper.NotifyDBLog(new Exception("Errore ModelState in Reset Password!"), "");
                return View("_IndexKO");
            }

        }

        private void UpdateForceChangePassword(int userId, bool force)
        {
            UserManager man = new UserManager();
            man.Update(new UserIdentificator(userId), "PasswordForceChange", force);

            Helper.CacheHelper.DeleteGroupCache(Keys.CacheKeys.GroupCacheUser);
        }

        


    }
}

inClub.Web/Portal/Views/RecuperaPassword/Index.cshtml
@model Inclub.Web.Portal.Models.UserResetPasswordForm
@using Inclub.Web.Portal.Helper
@using Inclub.Web.Portal.Extensions
@{


    Layout = "~/portal/Views/Shared/_LayoutRegistrazione.cshtml";
    var pageInfo = this.GetPageInfo();
}

<section>
    <div class="registerBox">
        <a href="/" class="back" title="Back">&lt; Back</a>
        <div class="container">
            <div class="box8">
                <div class="cntRegister">
                    <div class="box1">&nbsp;</div>
                    <div class="box6 formReg">
                        <h1>Modifica Password</h1>


                        @using (Html.BeginForm("ResetPassword", "RecuperaPassword", FormMethod.Post, new { id = "ResetPasswordForm" }))
                        {
                            @Html.ValidationSummary(true)
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(m => m.Id, (int)this.Model.Id);

                            <div class="rowForm">
                                <div class="box2">Nuova Password</div>
                                <div class="box4">@this.Html.PasswordFor(m => m.Password)</div>
                                <div class="box2 errorTxt"><span class="jsPrequired" style="display:none;">Compilare la Password</span></div>
                            </div>

                            <div class="rowForm">
                                <div class="box2">Conferma Password</div>
                                <div class="box4">
                                    @this.Html.PasswordFor(m => m.ConfirmPassword)
                                </div>
                                <div class="box2 errorTxt">
                                    <span class="jsCrequired" style="display:none;">Compilare Conferma Password</span>
                                    <span class="jsCMatch" style="display:none;">La Password non coincide</span>
                                </div>
                            </div>
                            

                            <div class="rowForm checkRow">
                                <div class="box2">&nbsp;</div>
                                <div class="box4" >
                                    <a href="javascript:void(0);"  style="width:83%;" title="Invia" class="btn" id="JResetPassword">Invia</a>
                                </div>
                                <div class="box2">&nbsp;</div>
                            </div>
                        }
                    </div>
                    <div class="box1">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</section>

@section JSscripts
{
    <script type="text/javascript">
        /*SCRIPT per FORM*/
        $(function () {
            $("#JResetPassword").click(function (e) {
                var procedi = true;
                $(".jsCrequired").hide();
                $(".jsCMatch").hide();
                $(".jsPrequired").hide();

                if ($("#Password").val() == '') {
                    $(".jsPrequired").show();
                    procedi = false;
                }

                if ($("#ConfirmPassword").val() == '') {
                    $(".jsCrequired").show();
                    procedi = false;
                }

                if ($("#ConfirmPassword").val() != '' && $("#Password").val() != '') 
                {
                    if ($("#ConfirmPassword").val() != $("#Password").val())
                    {
                        $(".jsCMatch").show();
                        procedi = false;
                    }
               }

                if (procedi == true)
                    {
                e.preventDefault();
                $('form#ResetPasswordForm').submit();
                }
            });

        });
    </script>
}

inClub.Web/Portal/Views/RecuperaPassword/_IndexKO.cshtml
@using Inclub.Web.Portal.Helper;
@using Inclub.Web.Portal.Keys;
@{
    var pageInfo = this.GetPageInfo();
}
<section>
    <div class="registerBox">
        <a href="/" class="back" title="Back">&lt; Back</a>
        <div class="container">
            <div class="box8">
                <div class="cntRegister">
                    <div class="box1">&nbsp;</div>
                    <div class="box6 formReg">
                        <h1>Modifica Password</h1>
                        <div class="rowForm">@this.Html.GetLabel(Inclub.Web.Portal.Keys.DictionaryKeys.ResetPWD_KO, Inclub.Web.Portal.Keys.LabelKeys.LANGUAGE_PORTAL)</div>
                    </div>
                    <div class="box1">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</section>

inClub.Web/Portal/Views/RecuperaPassword/_IndexOK.cshtml
@using Inclub.Web.Portal.Helper;
@using Inclub.Web.Portal.Keys;
@{
    var pageInfo = this.GetPageInfo();
}
<section>
    <div class="registerBox">
        <a href="/" class="back" title="Back">&lt; Back</a>
        <div class="container">
            <div class="box8">
                <div class="cntRegister">
                    <div class="box1">&nbsp;</div>
                    <div class="box6 formReg">
                        <h1>Modifica Password</h1>
                        <div class="rowForm">@this.Html.GetLabel(Inclub.Web.Portal.Keys.DictionaryKeys.ResetPWD_OK, Inclub.Web.Portal.Keys.LabelKeys.LANGUAGE_PORTAL)</div>                        
                    </div>
                    <div class="box1">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
</section>